version: 2

builds:
  - main: ./cmd/toktap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - deploy/config/*

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

dockers:
  - image_templates:
      - "ghcr.io/voska/toktap:{{ .Version }}"
      - "ghcr.io/voska/toktap:latest"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goarch: amd64
  - image_templates:
      - "ghcr.io/voska/toktap:{{ .Version }}-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goarch: arm64
